### ISSUE TITLE
Proposal to Add Gno Support in GitHub Linguist 

### ISSUE THREAD

**Issue by mous1985** [gnolang/gno#2999]
## Description
Hi,

I'd like to suggest adding `gno` language support to GitHub Linguist. This would allow GitHub to recognize ` .gno` files, with syntax highlighting and better visibility for Gno projects.

I've prepared the changes needed for integration into `languages.yml`
```yml
Gno:
  type: programming
  extensions:
    - .gno
  interpreters:
    - gno
  color: "#17202a"
  tm_scope: source.gno
  ace_mode: golang
Gno Module:
  type: data
  color: "#17202a"
  aliases:
  - gno.mod
  filenames:
  - gno.mod
  ``` 
I would appreciate a feedback to make a PR in the Linguist project of GitHub .
Thank you :)
