### ISSUE TITLE
[OPS] FEATURE REQUEST: Pruning system - sign and forget

### ISSUE THREAD

**Issue by albttx** [gnolang/gno#3637]
## Description

Currently, it is not possible to prune a node, all nodes store all blocks since block 1.

Once mainnet will arrive, there will be more transactions and storing all state since block 1 might create some storage issues on the nodes

There is multiple advantage about node pruning:

- reduce start-up time
- snapshots node are smaller, which make an easier and faster system to sync / recover / migrate a node.
- take less spaces on disks
- increase node performances

---

Another feature i would love to be implemented, which was already discuss once during a meeting with @jaekwon (long time ago) is the "Sign and forget" system.

Tendermint main bottleneck is disk usage, large chain must use NVMe for efficiency, an disks without pruning are growing really fast!

I believe a validator node don't require to store more than 1 block in memory, only the latest state should be required to store.

This feature i believe would increase BY A LOT performances, because we could almost get rid of disk usage and do everything in memory. If it's not done by code, it could be done by putting the `data/` dir into a `tmpfs` which is a in-memory file system.

FYI: On injective, with a ~1s block time, and the amount for txs, there is no possiblity to set the pruning because it cause a lot of block miss signature, and node is growing to couple hundreads of Gb in couple days...
A pruning from a pruned snapshot node is require every 1-2 week.

Of course, we might not have the same amount of txs from day 1, but if we start to have oracle writing in gno.land on every blocks, we could have node storage issues faster than we can expect.

cc: @moul @zivkovicmilos @gnolang/devops wdyt ?

ps: this issue will be mentioned in my gnops.io article i'm writing about snapshots node.

**Comment by n2p5** [comment]
Thanks for writing this up @albttx.

We should also make sure to outline the disadvantages and tradeoffs of node pruning.
Also do we have documentation on who the current pruning processes work? Is this a "stop the world" operation? Or can this be done concurrently on live nodes? Again, what are the tradeoffs and what is the block height thresholds we want to shoot for?

> FYI: On injective, with a ~1s block time, and the amount for txs, there is no possiblity to set the pruning because it cause a lot of block miss signature, and node is growing to couple hundreads of Gb in couple days...

What are the constraints here? and what is the cause of the misses?

> This feature i believe would increase BY A LOT performances, because we could almost get rid of disk usage and do everything in memory. If it's not done by code, it could be done by putting the data/ dir into a tmpfs which is a in-memory file system.

It would be cool to setup a small experiment to quantify what _A LOT_ looks like. Also I wonder if we could do some sort of WAL pattern where it goes RAMdisk > NVMe > block store with some sort of graceful degrade pattern. Sorting out what we can handle in churn and recorvery modes would be really interesting to sort out. 

For instance, in the Kubernetes world, I could see working with[ LocalPVs](https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/)  where we mount a RAMDisk and NVMe as part of the configuration with replication rules. Again, all of this stuff has tradeoffs, so it would be important to formulate small experiments as well as performing degraded state testing (cascading failure in assumptions, etc)

I love working on these types of problems and it could lead to some really nice generalization if we approach it correctly.

**Comment by albttx** [comment]
Good to add in this thread, the cosmos-sdk documentation for pruning

```toml
# default: the last 362880 states are kept, pruning at 10 block intervals
# nothing: all historic states will be saved, nothing will be deleted (i.e. archiving node)
# everything: 2 latest states will be kept; pruning at 10 block intervals.
# custom: allow pruning options to be manually specified through 'pruning-keep-recent', and 'pruning-interval'
pruning = "default"

# These are applied if and only if the pruning strategy is custom.
pruning-keep-recent = "0"
pruning-interval = "0"
```
